services:
  odoo_loyalty_api:
    image: node:18.20.2-alpine3.19
    container_name: odoo_loyalty_api
    restart: always
    # networks:
    #   - nginx_network
    #   - client_network
    entrypoint: sh
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: ['-c', 'if [ ! -d node_modules ]; then yarn; fi && yarn start']
# networks:
#   nginx_network:
#     external: true
#   client_network:
#     external: true
